name: 'Pulumi Config'
author: Simen A. W. Olsen
description: Update Pulumi configuration with Github Actions
branding:
  icon: upload-cloud
  color: purple
inputs:
  stack-name:
    description: 'Which stack you want to apply to, eg. dev'
    required: true
  work-dir:
    description: 'Location of your Pulumi files. Defaults to ./'
    required: true
    default: ./
  key:
    description: 'Set key value. e.g: service-name.tag'
    required: false
  value:
    description: 'Value to set'
    required: false
  secret:
    description: 'Store the config value as secret and hide it from output'
    required: false
    default: 'false'
  cloud-url:
    description: 'A cloud URL to log in to'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
