name: Update dist
on:
  push:
    branches: [main]

jobs:
  update-dist-and-release:
    name: Update dist files and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Use Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies 📦️
        run: yarn install --immutable

      - name: Build 🏗️
        run: yarn build

      - name: Commit dist files 📝️
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          file_pattern: dist/**
          add_options: -u --force
          commit_message: 'chore(dist): Update dist [automated commit]'
          commit_user_name: simenandre
          commit_user_email: so@bjerk.io
