name: Update dist
on:
  push:
    branches: [main]

jobs:
  update-dist-and-release:
    name: Update dist files and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          file_pattern: dist/**
          add_options: -u --force
          commit_message: 'chore(dist): Update dist [automated commit]'
          commit_user_name: simenandre
          commit_user_email: so@bjerk.io
